server:
    port: 8002

# database configuration
spring:
     datasource:
        url: jdbc:mysql://localhost:3306/inspecDB
        username: root
        password: root 
     jpa:
        properies:
              hibernate:
                   dialect: org.hibernate.MySQL5InnoDBDialect
                   format_sql: true
     application:
         name: VEHICLE-SERVICE